### ISSUE TITLE
bug in computing evaluation results across queries

### ISSUE THREAD

**Issue by laura-dietz** [ReazulHasan/TrecCar#10]
in line 80 and following TrecResultsParser you have a bug.

You only average results for rankings that were given to you. But you are not penalizing the case where a query is not answered with a ranking.

Example:
The task is to retrieve rankings for 100 queries.
But the system only returns a (non-empty) result for 20 of them.

Here an example where I simulated this for the test200-mock case.  (Github made me rename *run to  *txt )
[test200-mock2.txt](https://github.com/ReazulHasan/TrecCar/files/772507/test200-mock2.txt)

**Comment by ReazulHasan** [comment]
Thanks for mentioning, we didn't consider this specific case, I think. We'll check it out.

**Comment by blkfin** [comment]
Okay to use trec_eval from Trec, wrote a wrapper to use
