### ISSUE TITLE
Format for Evaluation

### ISSUE THREAD

**Issue by blkfin** [ReazulHasan/TrecCar#2]
Can we have the output of the Evaluation process be a list of ints (0 or 1) for non relevant/relevant based on the trec_eval formatted results in descending order of score? In trec_eval format listed rank is not guarantee

For example,
q1 q0 doc1 1 10 Run
q1 q0 doc3 2 8.2 Run
q1 q0 doc9 3 6    Run
q1 q0 doc2 4 1    Run

Where all docs returned are relevant except doc2 (meaning first 3 are matched in qrels "ground truth").  Output would be an int array =[1,1,1,0]

**Comment by ReazulHasan** [comment]
Hi, I think we can sort the list in descending order based on the score. But aren't the results of the evaluation process be Precision/Recall/F-Value etc.?

**Comment by blkfin** [comment]
That's right, I have just completed writing Precision, Recall,and F-value. I'll push class to github along with an associated test class now.  The input to these is the the 0,1 int list.  I'm now working on a calls that handles the average values for these (i.e. multiple queries).  I'm thinking that if we have a class that runs your input parser to get the int list, passes it to the Metrics class and then prints out the formatted results.  What do you think?

**Comment by blkfin** [comment]
Feel free to come up with a better name for the class also, that was the best I could think of, but I wouldn't mind something easier.

**Comment by ReazulHasan** [comment]
Your idea sounds good to me. The thing that you are thinking is like a middleman between the parser & the result calculator. right now the _getEvalData()_ method returns a list of _EvalData_ objects, the _relevance_ attribute of that object contains this 0/1 & that could be used, may be...

**Comment by blkfin** [comment]
Initial example updated to integrate using EvaluationDriver class as middleman between Evaluation parsing framework and performance measures.  Prints out results.

**Comment by blkfin** [comment]
No further action required on this
