### ISSUE TITLE
Project error

### ISSUE THREAD

**Issue by ReazulHasan** [ReazulHasan/TrecCar#3]
Hi Matt,

Were you using IntelliJ when working on the project? After I pulled the latest version from the repo, it's showing error in the ide, I can see that the classes: ClassificationBasedMetrics, ClassificationAggregatedMetrics etc. don't have any package specification at the beginning of the file.

**Comment by blkfin** [comment]
I was, for some reason our intellij environment configurations are different.  Feel free to modify the files to get them to work for you.  Next time, I'm in, we should try to figure out what the difference is between our environment settings.  Sound good? But in mean time do what you need to do to get them to work for you and I'll work from your updated version.

**Comment by ReazulHasan** [comment]
In my end, it's not able to find:

import org.junit.jupiter.api.BeforeEach;

any idea?

**Comment by ReazulHasan** [comment]
Cannot resolve symbol 'jupiter'

**Comment by blkfin** [comment]
The documentation on their unit testing isn't all that great, I used junit5 which is the source of the jupiter reference.  I tried running on another computer and it worked fine for me, so unfortunately, I can't replicate the error.   I don't know if this will help or not.  https://blog.jetbrains.com/idea/2016/08/using-junit-5-in-intellij-idea/  I'm fine with scrapping the maven structure for this project, if you wanted to create a fresh one and add the files to it.  It might help with resolving the dependencies.

**Comment by ReazulHasan** [comment]
Adding below dependency  into the pom.xml file resolved the issue for me.

    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-api</artifactId>
      <version>5.0.0-M3</version>
      <scope>test</scope>
    </dependency>
