### ISSUE TITLE
Work Plan

### ISSUE THREAD

**Issue by blkfin** [ReazulHasan/TrecCar#4]
Let me know what you
think of the updates and what you think we should do as next steps,
i.e. what remaining work to we have to do and who should do it.

I think this is actually pretty close to done functionally and now
just needs some refinement/additional testing/etc to be respectable
for turning in.

A couple of areas I see are:
1. Javadocs
2. making the EvaluationDriver generic to accept any groundtruth, trec
results, and topic id
3. updating EvaluationDriver to handle multiple topicids in addition to just one
4. Some additional unit tests using other trec formatted files and queryids
5. Final product - making sure it Maven can build completely.

I can work on this today, so if you can let me know what you think
about what we should work on, so we don't duplicate efforts.  Thanks

**Comment by ReazulHasan** [comment]
I'm not completely sure about 2 & 3... about the task 2, during my parsing from the file, I'm maintaining a multimap which keeps a list of values (paragraph ids, relevance) for each key (topic id). If a topic id appears multiple times, it adds the value on the same list. when searching with a key, it returns the list that contains the corresponding values. Is it different than what you are thinking?
