### ISSUE TITLE
EvaluationDriver Signature

### ISSUE THREAD

**Issue by blkfin** [ReazulHasan/TrecCar#5]
Can your provide  the argument signature for EvaluationDriver? I think we should have a main argument for command line but also a constructor for EvaluationDriver. If you haven't created yet, does EvaluationDriver(qrels_file, results_file) work for you? I'm going to start coding up unit tests for it.

**Comment by blkfin** [comment]
To follow-up on todays conversation, let's go with EvaluationDriver(String qrels_file, String results_file)  for constructor signature and EvaulationDriver <qrels_file> <results_file> for command line arguments.

**Comment by ReazulHasan** [comment]
This sounds reasonable.
