### ISSUE TITLE
Update Evaluation Class to parse multiple queries

### ISSUE THREAD

**Issue by blkfin** [ReazulHasan/TrecCar#6]
1. Have Evaluation class parse a file with multiple queries in one file (  for example TrecCar/results/results.spritzer.cbor.article.qrels.2.test).  
2. Create a method in Evaluation  getRelevencyResults that returns an ArrayList<RelevancyResult> for each query parsed.  For RelevancyResult object,  String query is the query like "green%20sea%20turtle" and relevancyResults can be obtained by calling the int[] getRelevancyResults method.

**Comment by ReazulHasan** [comment]
Multiple query is parsed & is accessible as below:

Evaluation eval = new Evaluation(arg[0], arg[1]); //arg[0]->ground truth, arg[1]->evaluation data
ArrayList< EvalData > al = eval.getEvalData("Green%20sea%20turtle");
for(EvalData ed : al){
        System.out.println("id: "+ed.getId());
}
