### ISSUE TITLE
Total Relevant Results Method for Evaluation Class

### ISSUE THREAD

**Issue by blkfin** [ReazulHasan/TrecCar#7]
Can you create a method that does the following

public int getTotalRelevantDocuments(String query)
  //Returns a count of all documents that match the query in the qrels file
  //For example if query is "green%20sea%20turtle"
  // goes through the qrel file and counts all relevant documents matching that request

**Comment by ReazulHasan** [comment]
Two methods are provided:

public int getCountRelevant**GroundTruth**(String query)
public int getCountRelevant**EvalData**(String query)

Please check & confirm whether they suffice the requirement.

**Comment by blkfin** [comment]
Perfect, thanks
